### ISSUE TITLE
add Safe Call Operator on DateTime map[key]

### ISSUE THREAD

**Issue by marcos930807** [vanlooverenkoen/moor_db_viewer#19]
In my case i have some dateTime that are null, and  dateTime.toIso8601String(); rise a null pointer Exception.
Please add safe call ? operator

**Comment by vanlooverenkoen** [comment]
Thanks for reporting. I will fix this issue tomorrow.

**Comment by vanlooverenkoen** [comment]
This pretty view should also be an option #20

**Comment by vanlooverenkoen** [comment]
fixed in 2.0.2
