### ISSUE TITLE
Add @UseRowClass support

### ISSUE THREAD

**Issue by jbrechbuehl** [vanlooverenkoen/moor_db_viewer#45]
Hello,

it seems MoorDbViewer doesn't work with Table annotation `@UseRowClass`. 
I got the error message: 

`The following _CastError was thrown while handling a gesture:
type '$SettingsTable' is not a subtype of type 'TableInfo<Table, DataClass>' in type cast
`

Thanks

**Comment by jbrechbuehl** [comment]
I just changed line 68 of file `db_navigator.dart` from:
`final table = settings.arguments as TableInfo<moor.Table, DataClass>;`
to
`final table = settings.arguments as TableInfo<moor.Table, dynamic>;`
and it seems to work.

**Comment by vanlooverenkoen** [comment]
I will fix that right away

**Comment by vanlooverenkoen** [comment]
4.3.0 Is released
