### ISSUE TITLE
Support to newest version of moor

### ISSUE THREAD

**Issue by PawelHryniewiecki** [vanlooverenkoen/moor_db_viewer#47]
Hello when i upgarde moor to lastest version i have exception like this.
`
Because moor_db_viewer 4.3.0 depends on provider ^5.0.0 and no versions of moor_db_viewer match >4.3.0 <5.0.0, moor_db_viewer ^4.3.0 requires provider ^5.0.0.
So, because my_app depends on both moor_db_viewer ^4.3.0 and provider ^6.0.0, version solving failed.
pub get failed (1; So, because my_app depends on both moor_db_viewer ^4.3.0 and provider ^6.0.0, version solving failed.)`

**Comment by juliangeissler** [comment]
I wrote an upgrade here https://github.com/vanlooverenkoen/moor_db_viewer/pull/46
Maybe you can look over it

**Comment by vanlooverenkoen** [comment]
I will take a look at it today. I am just back from holiday

**Comment by vanlooverenkoen** [comment]
published 4.4.0
