### ISSUE TITLE
Upgrade to support Drift v2.0.0

### ISSUE THREAD

**Issue by frankvollebregt** [vanlooverenkoen/moor_db_viewer#53]
The drift v2.0.0 update with breaking changes was released yesterday. It would be very useful if this package could also receive an update to work with this new version.

The most notable breaking change seems to be that types (in TypeConverters etc) are now using the non-nullable types, like `int` instead of `int?`.

**Comment by vanlooverenkoen** [comment]
2.0.0 is released on pub.dev
